################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
"""
"""
cimport stlcontainers
from libc.stdlib cimport free
from libcpp.map cimport map as cpp_map

import collections
import stlcontainers



cdef class A:
    """no docstring for {'sidecars': (), 'tarbase': 'hoover', 'tarname': 'A', 'language': 'c++', 'srcname': 'A', 'incfiles': ('hoover.h',), 'srcfiles': ('src/hoover.h', 'src/hoover.cpp')}, please file a bug report!"""



    # constuctors
    def __cinit__(self, *args, **kwargs):
        self._inst = NULL
        self._free_inst = True

        # cached property defaults
        self._y = None

    def __init__(self, x=5):
        """A(self, x=5)
        """
        self._inst = new cpp_hoover.A(<int> x)
    
    
    def __dealloc__(self):
        if self._free_inst:
            free(self._inst)

    # attributes
    property y:
        """no docstring for y, please file a bug report!"""
        def __get__(self):
            cdef stlcontainers._MapIntDouble y_proxy
            if self._y is None:
                y_proxy = stlcontainers.MapIntDouble(False, False)
                y_proxy.map_ptr = &(<cpp_hoover.A *> self._inst).y
                self._y = y_proxy
            return self._y
    
        def __set__(self, value):
            cdef stlcontainers._MapIntDouble value_proxy
            value_proxy = stlcontainers.MapIntDouble(value, not isinstance(value, stlcontainers._MapIntDouble))
            (<cpp_hoover.A *> self._inst).y = value_proxy.map_ptr[0]
            self._y = None
    
    
    # methods
    

    pass






{'cpppxd_footer': '', 'pyx_header': '', 'pxd_header': '', 'pxd_footer': '', 'cpppxd_header': '', 'pyx_footer': ''}
