################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################


cimport hoover
from mypack cimport cpp_hoover_b

cdef class B(hoover.A):
    pass




