################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################
"""
"""
cimport hoover
from mypack cimport cpp_hoover

import hoover

cdef class B(hoover.A):
    """no docstring for B, please file a bug report!"""

    # constuctors
    def __cinit__(self, *args, **kwargs):
        self._inst = NULL
        self._free_inst = True

        # cached property defaults


    def __init__(self):
        """B(self)
        """
        self._inst = new cpp_hoover_b.B()
    
    

    # attributes
    property z:
        """no docstring for z, please file a bug report!"""
        def __get__(self):
            return int((<cpp_hoover_b.B *> self._inst).z)
    
        def __set__(self, value):
            (<cpp_hoover_b.B *> self._inst).z = <int> value
    
    
    # methods






